#### 参考链接：
* [pytorch官方教程](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

**pytorch是什么？**
* 取代numpy，专门用于GPU计算

In [1]:
from __future__ import print_function
import torch

### tensor的创建
* torch.empty(5, 3):没有初始化的矩阵
* torch.rand(5,3):随机初始化
* torch.zeros(7, 3, dtype=torch.long):初始化为0，并指定数据类型为long
* torch.tensor([23.23, 0.23,29823998,32023])：将已有数据转变为tensor,列表中存有数据
* x = x.new_ones(2, 2, dtype=torch.double):将已有的tensor变为新的tensor，并指定类型
* x = torch.randn_like(x, dtype=torch.float):改变已有tensor变量类型并将其创建为新的tensor

### tensor的常用操作
* x.size() :返回一个tuple，用于反映tensor维度，该tuple支持一切元组操作
* tensor加法的语法（x,y为同等大小tensor）：
    * print(x + y)
    * print(torch.add(x, y))
    * result = torch.empty(5, 3),torch.add(x, y, out=result)  ：将运算结果存在定义的result张量中
    * y.add_(x)   ：带有后缀_会改变参与运算的张量的值，这里原有y信息丢失
* print(x[:, 2])   ：取tensor的第三列，操作方法与numpy索引一致
* z = x.view(-1, 8) ：改变tensor的维度，the size -1 is inferred from other dimensions
* x.item()       ：one element tensor，get the value as a Python number.


### [更多tensor的操作](https://pytorch.org/docs/stable/torch.html)

### tensor与numpy的转换
**注意点：火炬张量和numpy数组(转换前后)将共享其底层内存位置（如果火炬张量在CPU上），更改一个将更改另一个。**
numpy1 = tensor1.numpy() : tensor --> numpy
tensor2 = torch.from_numpy(numpy2):numpy -->tensor

### CUDA Tensors
Tensors can be moved onto any device using the .to method.

### tensor的创建

* tensor与numpy中的多维数组ndarrays相似，但是**tensor可以在GPU中加速运算**

In [2]:
# 1 declare an uninitialized matrix,
# 2 don't contain definite known values before it is used.
# 3 whatever values were in the allocaoted at the time will appear as the initial values(如果不专门初始化，分配的内存中的值将会作为初始值)
x = torch.empty(5, 3)   # 声明一个未初始化矩阵
print(x)

tensor([[8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39],
        [1.0378e-38, 9.6429e-39, 9.2755e-39],
        [1.0928e-38, 9.9184e-39, 0.0000e+00]])


In [19]:
x = torch.rand(5,3)   # construct a randomly initialized martrix(声明矩阵，并随机初始化)
print(x)

tensor([[0.5389, 0.3563, 0.7202],
        [0.0048, 0.7399, 0.5728],
        [0.8696, 0.7727, 0.7794],
        [0.9452, 0.6700, 0.4919],
        [0.6068, 0.6264, 0.9549]])


In [23]:
x = torch.zeros(7, 3, dtype=torch.long)  # construct a matrix filled zeros and of dtyoe long
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [48]:
x = torch.tensor([23.23, 0.23,29823998,32023]) # construct a tensor directly from data
print(x)

x = x.new_ones(2, 2, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)   

tensor([2.3230e+01, 2.3000e-01, 2.9824e+07, 3.2023e+04])
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[ 0.2478, -0.6487],
        [-0.6725,  0.6654]])


In [56]:

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)
x = torch.randn_like(x)                       # 继承了之前tensor的类型
print(x)
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.1434,  0.4270, -1.8853],
        [ 0.7491,  1.0260,  1.1579],
        [ 2.1681, -0.9536,  1.3202],
        [ 0.0486,  1.8332, -0.8583],
        [-0.8186,  0.1031,  1.1943]], dtype=torch.float64)
tensor([[ 0.0566, -0.2815, -1.3402],
        [ 0.0433, -1.7631,  1.4269],
        [ 1.2746, -0.8874,  1.4833],
        [-0.9965,  1.8236, -0.3645],
        [ 2.0717, -1.2871, -0.3986]])


### tensor的常用操作

In [68]:
print(x.size())     # torch.size in fact a tuple,so it supports all tuple operations
d = x.size()[1]     
print(d)

torch.Size([5, 3])
3


In [71]:
print(x)
y = torch.rand(5,3)
print(y)

tensor([[ 0.0566, -0.2815, -1.3402],
        [ 0.0433, -1.7631,  1.4269],
        [ 1.2746, -0.8874,  1.4833],
        [-0.9965,  1.8236, -0.3645],
        [ 2.0717, -1.2871, -0.3986]])
tensor([[0.9763, 0.4136, 0.5451],
        [0.9530, 0.6346, 0.2831],
        [0.3156, 0.0083, 0.3041],
        [0.8070, 0.2229, 0.6649],
        [0.4117, 0.2119, 0.5572]])


In [74]:
print(x + y)
print(torch.add(x, y))
t = x+y
print(t)

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0328,  0.1321, -0.7950],
        [ 0.9963, -1.1285,  1.7100],
        [ 1.5902, -0.8792,  1.7874],
        [-0.1895,  2.0464,  0.3004],
        [ 2.4835, -1.0752,  0.1586]])
tensor([[ 1.0328,  0.1321, -0.7950],
        [ 0.9963, -1.1285,  1.7100],
        [ 1.5902, -0.8792,  1.7874],
        [-0.1895,  2.0464,  0.3004],
        [ 2.4835, -1.0752,  0.1586]])
tensor([[ 1.0328,  0.1321, -0.7950],
        [ 0.9963, -1.1285,  1.7100],
        [ 1.5902, -0.8792,  1.7874],
        [-0.1895,  2.0464,  0.3004],
        [ 2.4835, -1.0752,  0.1586]])
tensor([[ 1.0328,  0.1321, -0.7950],
        [ 0.9963, -1.1285,  1.7100],
        [ 1.5902, -0.8792,  1.7874],
        [-0.1895,  2.0464,  0.3004],
        [ 2.4835, -1.0752,  0.1586]])


In [75]:
# adds x to y
y.add_(x)   # have post-fixed with an _,会改变本来的值，这里计算x+y,是将y存储运算结果，原有的y丢失
print(y)

tensor([[ 1.0328,  0.1321, -0.7950],
        [ 0.9963, -1.1285,  1.7100],
        [ 1.5902, -0.8792,  1.7874],
        [-0.1895,  2.0464,  0.3004],
        [ 2.4835, -1.0752,  0.1586]])


In [77]:
print(x)
print(x[:, 2])  # 取tensor的第三列，操作方法与numpy索引一致

tensor([[ 0.0566, -0.2815, -1.3402],
        [ 0.0433, -1.7631,  1.4269],
        [ 1.2746, -0.8874,  1.4833],
        [-0.9965,  1.8236, -0.3645],
        [ 2.0717, -1.2871, -0.3986]])
tensor([-1.3402,  1.4269,  1.4833, -0.3645, -0.3986])


In [87]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [89]:
x = torch.randn(1)
print(x.item())  # 将one item tensor 转换位value

1.0357784032821655


### tensor与numpy的转换

In [96]:
tensor1 = torch.ones(5)
print(tensor1)
numpy1 = tensor1.numpy()
print(numpy1)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [106]:
import numpy as np
numpy2 = np.ones(5)
tensor2 = torch.from_numpy(numpy2)
np.add(numpy2, 1, out=numpy2)
print(numpy2)
print(tensor2)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

In [107]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2.0358], device='cuda:0')
tensor([2.0358], dtype=torch.float64)
